import React, { useState, useEffect } from "react";

function Homepage() {
  useEffect(() => {
    let scrollVideo = () => {
      console.log("scrolled");
    };
    window.addEventListener("scroll", scrollVideo);
    return () => {
      window.removeEventListener("scroll", scrollVideo);
      console.log("event detached");
    };
  }, []);
  return (
    <div>
      <video id="waterfall" src="waterfall.mp4" type="video/mp4" muted loop autoPlay></video>
      <div className="contents" style={{ color: "white" }}>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam nulla quasi corrupti quidem veritatis reiciendis impedit explicabo incidunt, accusamus ipsam earum atque officia eveniet facilis amet. Praesentium eos suscipit nobis ducimus. Soluta consequatur, pariatur est adipisci animi ullam. Ab ratione deserunt quis optio architecto veritatis totam vero officia, quod provident expedita porro, vel exercitationem, nesciunt iure odio. Ratione, accusantium obcaecati. Necessitatibus eligendi impedit facere ea recusandae accusantium? Quam ipsa laborum dolor molestiae eveniet cumque reprehenderit nemo vel fugiat molestias enim, odio amet, perferendis eligendi aut, accusantium architecto maxime nesciunt tempore! Quos voluptatem odio architecto molestiae expedita cumque, sequi dolore voluptates non. Laudantium, distinctio unde excepturi quod labore perspiciatis ut, nihil hic, odit dolore ab! Rerum sequi architecto recusandae tempora voluptatem doloribus necessitatibus ab incidunt
        consequuntur atque numquam, eaque eius nesciunt dolorum soluta voluptas vitae porro, omnis perferendis tempore, maiores deserunt. Quas culpa temporibus, unde repellendus recusandae laboriosam ex ad voluptas necessitatibus voluptates repudiandae voluptatem fugit amet enim labore quibusdam voluptatum facere eaque provident odit aliquid officia? Repellat at esse veritatis impedit quaerat sunt laudantium adipisci qui voluptas ratione officia, vero delectus eum animi! Veniam aliquid sit illo minima assumenda facilis reprehenderit modi, veritatis aperiam necessitatibus laudantium quod iste. Deserunt optio nobis provident amet, est unde pariatur facilis natus sunt vitae voluptas adipisci? Beatae sit eos, eius recusandae totam, consectetur dolorem suscipit, autem fugit omnis hic! Quis nostrum, eaque quod id sit vero, dolorem magnam pariatur esse, quos itaque repudiandae expedita. Modi eos voluptate ratione, ducimus magni consectetur adipisci qui, autem doloribus suscipit tempore. Earum
        quod deleniti nulla perspiciatis soluta est a quis veritatis tempora provident nihil iusto repudiandae, esse dolorum hic quisquam mollitia eaque nemo eveniet? Voluptatum earum doloremque possimus eaque sapiente magnam corrupti adipisci mollitia fuga id ratione, voluptas officia itaque. Animi quasi fugit, ratione dolor inventore recusandae neque commodi molestiae sit totam, fuga, assumenda impedit quo. Dignissimos consequuntur sequi commodi adipisci natus ullam, animi provident consectetur dolore repudiandae nam id in sunt. Ad, veniam magnam ipsa tempora, architecto animi earum dolorem optio modi numquam, iusto quasi nemo porro? Necessitatibus, assumenda omnis, quos distinctio maiores aperiam nam esse reprehenderit similique porro explicabo fugit voluptate est beatae neque pariatur labore corporis, eveniet consequatur perspiciatis eligendi molestias! Quo aperiam rerum reiciendis, ducimus sunt velit et, atque non temporibus officia animi officiis enim, delectus illum error
        dignissimos! Minus mollitia ex sequi, velit, consequuntur praesentium odit placeat quod eligendi officiis quisquam? Pariatur libero error optio necessitatibus cumque tempora dicta. Iure, sed minima totam itaque ipsa porro cupiditate consectetur. Laudantium laboriosam tenetur numquam. Molestiae labore delectus voluptatibus doloremque nulla non eaque quos enim voluptatem, voluptatum laudantium harum sapiente saepe necessitatibus quae voluptas, modi itaque! Totam reprehenderit corporis illo assumenda incidunt ex enim in unde maiores numquam blanditiis mollitia, voluptatibus adipisci dolore eligendi Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae dolores architecto, debitis dolorem odio repellat rem natus aliquid perferendis provident ut deleniti laudantium eveniet voluptatum sapiente fugit consectetur. Delectus veniam, odio sapiente totam ex eaque culpa, ipsa sint repudiandae repellendus porro aspernatur nesciunt. Placeat quam minima cumque reiciendis aspernatur
        beatae sapiente dolore, quas quis nihil aperiam nisi repellendus reprehenderit, deleniti sint distinctio dolores voluptates accusamus. Reprehenderit eos, dolorum nemo placeat error, quia aspernatur assumenda sequi, doloremque neque amet exercitationem dolores. Alias, atque unde reprehenderit commodi rem a. Quidem aperiam voluptas atque tempora cum earum modi fuga pariatur! Ut doloribus placeat minima ratione id cumque ipsum beatae excepturi. Consectetur labore debitis ad excepturi quas doloribus sunt sit voluptas a nostrum eius at dolore obcaecati illo pariatur, nihil laudantium totam harum. Velit maiores perferendis atque eaque tempora perspiciatis quidem illo earum ullam molestiae assumenda voluptatem esse rerum facere, odit necessitatibus mollitia reprehenderit sed. Libero cupiditate quam provident vero nulla magnam non, consequatur expedita tenetur quibusdam aperiam delectus rerum perspiciatis id ducimus voluptas! Similique, eveniet. Provident, dolores labore aut placeat
        totam veniam fugiat sequi enim illo rem officia. Voluptatem harum, voluptates, debitis aperiam praesentium sed accusamus neque laborum error, officiis doloremque laudantium esse fugit? Magnam, at consequuntur eligendi voluptatibus, aspernatur voluptate, voluptatem temporibus est possimus iure suscipit. Soluta ipsam cum nostrum tenetur, error molestias unde pariatur minus ducimus possimus quos recusandae nisi accusamus! Temporibus provident eius reiciendis distinctio, quod non quasi ex suscipit ipsa harum blanditiis numquam beatae. Eaque error perferendis tempore numquam ullam eveniet illum sequi? Et tenetur mollitia, eum maxime corporis ab perferendis eaque aspernatur earum itaque autem facere voluptate, cumque ipsum velit repudiandae eos ex perspiciatis possimus beatae labore nihil libero? Quas rerum libero eligendi repudiandae ratione recusandae voluptate a unde deserunt blanditiis impedit non dignissimos quod nihil pariatur eaque doloremque similique, commodi excepturi iure
        ut. Deserunt voluptatem consequatur voluptatibus? Adipisci ea quam esse ut asperiores. Optio distinctio consequatur vitae harum impedit quas iusto eius fuga sit minus! Nesciunt mollitia quaerat reiciendis nihil non consequuntur voluptates, dignissimos tempora nemo quia iure ad. Unde voluptatem quia explicabo ea illo optio veritatis nesciunt magni exercitationem cumque quas eveniet quis odio earum nam, laborum libero minima iusto! Vero, deserunt facilis. Illum aspernatur aliquam sunt, ut adipisci odio magni nostrum numquam facere eos dolor sint non totam quos vitae consequatur tempore minima possimus labore animi? Neque laborum tempore exercitationem beatae ratione, itaque nobis at et dicta corporis dolore consectetur, ducimus animi quae in harum cum ex est! Eveniet dolorem dolor quia quis recusandae ad beatae ducimus quisquam totam quas, ut quo eligendi voluptatum nobis nulla, a temporibus. Perspiciatis suscipit nemo incidunt corrupti, architecto asperiores laborum aperiam iure
        quia, cum harum eaque ab, perferendis quod temporibus magni soluta delectus quidem dolor aut eum voluptates laudantium modi. Voluptatibus excepturi perferendis impedit id illum, vel necessitatibus corrupti ex culpa facilis delectus recusandae voluptates? Nobis consectetur voluptatum, sequi explicabo earum dolorem! Repudiandae nobis vel excepturi facere sapiente doloremque nihil rem minus quisquam iure impedit voluptatibus neque ipsa accusamus quas hic accusantium sit, assumenda placeat, tempore reprehenderit ipsum error optio eius. Repellat eveniet provident neque voluptatem culpa obcaecati dolore exercitationem vel. Beatae dolorem fuga cupiditate nobis, quam laudantium quibusdam! Saepe dicta itaque voluptate corporis exercitationem repellendus odio, vitae dolor doloribus iusto, aperiam iure accusantium quasi quo dolorem, natus alias. Temporibus, ullam sed dolorum adipisci, fugit repudiandae vero modi nobis, commodi atque dolorem porro sint eveniet magni? Rerum culpa
        repudiandae quas minus ipsa harum delectus sit corrupti quis vitae? Dolorum distinctio a exercitationem incidunt necessitatibus ratione magni tempore praesentium rem vitae, minima cum, placeat adipisci harum voluptates sapiente corrupti? Expedita ducimus, porro dolor reprehenderit explicabo voluptas, pariatur laborum corporis reiciendis officiis blanditiis. Maxime placeat enim a, saepe magnam harum eveniet vitae sunt molestias, odio architecto ipsum iste ullam minima culpa dolore accusamus similique repellat et! Optio nulla recusandae illo minus error perferendis, nisi voluptates accusantium libero earum distinctio saepe delectus quo quos iure reprehenderit quidem! Temporibus laudantium, quibusdam recusandae a, autem ipsum minima pariatur quis placeat voluptas repellat fugit, illo vel assumenda dignissimos nemo eveniet eius. Sed iure molestias dolorum quo fugit quod cumque velit, dolorem, voluptatem, ipsam consequatur earum! Itaque laboriosam nostrum corporis voluptates
        blanditiis dolorum ex magnam aut expedita distinctio nemo inventore dolores doloribus, ab laudantium praesentium recusandae consequatur amet! Numquam possimus quos vel ad exercitationem molestiae? Possimus rem illum quisquam dolore deleniti mollitia laborum sit consequuntur at aliquid doloribus odit natus iure voluptas, delectus, sed iste! A accusamus voluptatem, sint est error accusantium eos quis provident non eius temporibus perferendis laudantium illo deleniti debitis quisquam natus suscipit iusto laboriosam voluptas asperiores corrupti repellat neque! Optio magnam non repellendus quo dignissimos quam tempora recusandae. Repudiandae quis et ipsum id adipisci consequuntur quasi, possimus sed eveniet amet praesentium, esse aliquam illo laudantium similique nesciunt accusantium temporibus fugit alias quam aperiam. Nam repellendus, eligendi sequi suscipit explicabo nihil atque excepturi quis quod eveniet labore commodi consectetur incidunt laborum aspernatur doloribus? Quae
        earum eveniet itaque. Fugiat, veritatis soluta voluptatem quae magni quos mollitia aliquid totam explicabo, aperiam praesentium enim vero consequuntur, est a non doloremque quibusdam alias neque optio dolor. Neque veritatis laborum dolorem accusantium vitae, nulla magni, labore quisquam eum at assumenda. Error maxime sunt asperiores dolorem suscipit, harum quasi vitae molestiae odit ipsa, qui, eveniet nostrum alias quam. Ratione necessitatibus quos quibusdam veritatis delectus repellat fuga, quia accusantium animi? Nostrum sint est illum. At aut iure, tempora enim, beatae sequi odit, veniam quaerat laudantium blanditiis est accusantium! Fugit consectetur numquam tempora incidunt. Laboriosam impedit magni voluptatem labore ipsam quisquam sit nemo consectetur nulla fuga culpa, vitae, sequi pariatur, perspiciatis ratione reiciendis reprehenderit facilis veritatis nisi atque. At suscipit, ab commodi temporibus voluptatum odit porro iste vero. Cupiditate accusamus, ea necessitatibus
        quis sequi consequuntur optio inventore obcaecati repellat iure est temporibus natus laudantium quo minima sapiente quas quidem, ut numquam dolorum doloribus, quasi sunt! Commodi, necessitatibus suscipit. Eius, natus! Labore voluptate, voluptatibus autem magni consectetur iste possimus, velit temporibus, harum cupiditate tempore eligendi saepe! Quod vero sed odit adipisci omnis.dolorum dolores tenetur neque accusantium perspiciatis, at inventore? Corrupti, modi. Et reiciendis autem eligendi consequuntur, accusantium voluptatem blanditiis debitis, esse delectus natus asperiores. Repellendus perspiciatis odit quis suscipit amet eius, dicta labore quisquam provident quasi dolores! Minima optio ullam vero sapiente? Nihil?
      </div>
    </div>
  );
}

export default Homepage;
